version: '3'

services:
  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    networks:
      - development1
  authenticationDBMigration:
    image: authentication_db_migration_image
    environment:
      - DATABASE_URL=authenticationDB
    depends_on:
      authenticationDB:
        condition: service_healthy
    networks:
      - development1
  authentication:
    image: authentication_image
    environment:
      - DATABASE_URL=authenticationDB
    depends_on:
      - authenticationDBMigration
    ports:
      - 5002:5002
    networks:
      - development1
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - development1

networks:
  development1: